### ISSUE TITLE
Missing `algorithm` import in `pq_utils`

### ISSUE THREAD

**Issue by obackhouse** [edeprince3/pdaggerq#35]
I get the following compilation error:

`error: ‘remove_if’ is not a member of ‘std’ `

which can be fixed by adding `#include<algorithm>` here:

https://github.com/edeprince3/pdaggerq/blob/0860ca23b4f68dde2e86dea379718e18fd19ce39/pdaggerq/pq_utils.h#L27-L29

**Comment by edeprince3** [comment]
thanks!
