### ISSUE TITLE
Quickstart: `print_fully_contracted` does not exist

### ISSUE THREAD

**Issue by jagunther** [edeprince3/pdaggerq#53]
Hi there!

I am trying out your code and ran the Quickstart script. I noticed that `pq.print_fully_contracted()` does not seem to exist:

`AttributeError: 'pdaggerq._pdaggerq.pq_helper' object has no attribute 'print_fully_contracted'`

However, `pq.print()` works fine.

Cheers!

**Comment by edeprince3** [comment]
Whoops, you are right! Thanks for the report.
