### ISSUE TITLE
example with spins: integrals, Fock matrices etc.

### ISSUE THREAD

**Issue by mkrompiec** [edeprince3/pdaggerq#72]
Thank you for making pdaggerq public. Can you share a full example for ccsd_with_spin, i.e. unrestricted CCSD? My own attempts are getting nowhere so far...

**Comment by mkrompiec** [comment]
Specifically, it would be great to see how to setup the calculation (integrals, Fock operators etc). I suppose any example of an UHF-based method would do.

**Comment by edeprince3** [comment]
a UCCSD example with integrals from psi4 is called here:

https://github.com/edeprince3/pdaggerq/blob/46f891c2dbaba598f3a315833bbea58b9fd78c36/examples/psi4_interface/cc_example.py#L65

That function in turn calls ccsd_with_spin:

https://github.com/edeprince3/pdaggerq/blob/46f891c2dbaba598f3a315833bbea58b9fd78c36/examples/psi4_interface/cc_tools.py#L321

That function calls get_integrals_with_spin, which builds all the objects you mentioned:

https://github.com/edeprince3/pdaggerq/blob/46f891c2dbaba598f3a315833bbea58b9fd78c36/examples/psi4_interface/cc_tools.py#L194

**Comment by mkrompiec** [comment]
Thanks a lot! I want to use it with pyscfad, but the psi4 example is a good
starting point.
